input_source: "/home/orin/dinov3_2/00015.jpeg"
is_video: false
fp16: false

unified_weights: "models/unified_model.pth"
backbone_weights: "models/dinov3_vits16plus.pth"
dino_dir: "modules/dinov3"
dino_model_type: "dinov3_vits16plus"
class_names: "src/rvinci/projects/dinov3_inf/configs/classes.txt"

image_size: 640

dinov3_config:
  num_classes: 1
  n_layers: 12
  embed_dim: 384
  depth_out_size: [640, 640]
  seg_target_size: [160, 160]
